package me.naptie.pulse

object UiStrings {
    const val appTitle = "Pulse"
    const val appSubtitle = "Vitals, live"
    const val tabDevices = "Devices"
    const val tabVitals = "Vitals"
    const val scanning = "Scanning…"
    const val scanForDevices = "Scan for devices"
    const val noDevicesYet = "No devices yet — tap Scan to\nfind a monitor"
    const val unnamedDevice = "Unnamed device"
    const val hrBadge = "HR"
    const val o2Badge = "O2"
    const val dbm = "dBm"
    const val bpm = "BPM"
    const val percent = "%"
    const val zoneRest = "Rest"
    const val zoneNormal = "Normal"
    const val zoneElevated = "Elevated"
    const val zoneExercise = "Exercise"
    const val zonePeak = "Peak"
    const val zoneAttention = "Attention"
    const val zoneLow = "Low"
    const val last5Minutes = "LAST 5 MINUTES"
    const val notMonitoring = "Not monitoring"
    const val notMeasuring = "Not measuring"
    const val noDeviceYet = "No device yet"
    const val tapStartToMeasure = "Tap start to measure"
    const val waitingForData = "Waiting for data…"
    const val simulatingVitals = "Simulating vitals…"
    const val findYourSensor = "Find your sensor in Devices"
    const val startMeasuringToRecord = "Start measuring to record your vitals"
    const val stopMeasuring = "Stop measuring"
    const val startMeasuring = "Start measuring"
    const val findADevice = "Find a device"
    const val couldntConnect = "Couldn't connect"
    const val tryAgain = "Try again"
    const val ok = "OK"

    const val connectionLost = "Connection lost"
    const val stopped = "Stopped"
    const val connected = "Connected"
    const val bluetoothUnavailable = "Bluetooth unavailable"
    const val monitorServiceNotFound = "Monitor service not found"

    fun connectedWith(name: String) = "Connected · $name"
    fun nameNotMeasuring(name: String) = "$name · $notMeasuring"
}
